# -*- coding: utf-8 -*-
"""tugas akhir deep learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VqgA5hT4ilOSJhQ2jnJQhfk_ywqctsLV
"""

# ==============================================================================
# 1. PERSIAPAN LINGKUNGAN DAN PEMUATAN DATA
# ==============================================================================

# Instal TensorFlow dan Keras jika belum ada (biasanya sudah ada di Colab)
# !pip install tensorflow pandas numpy scikit-learn matplotlib

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Nama file yang telah Anda unggah
file_name = 'hargaa baru(2).csv'

# Baca data
df = pd.read_csv(file_name)

print("Lima baris pertama data:")
print(df.head())
print("\nInformasi Data:")
print(df.info())

# ==============================================================================
# 2. PRA-PEMROSESAN DATA
# ==============================================================================

# Konversi kolom 'tanggal' menjadi tipe data datetime
df['tanggal'] = pd.to_datetime(df['tanggal'])
df.set_index('tanggal', inplace=True)

# Pilih kolom harga
data = df[['harga']].copy()

# Penanganan Nilai Hilang (Missing Values)
# Untuk data time series, metode 'ffill' (forward fill) sering digunakan untuk
# mengisi nilai yang hilang dengan nilai sebelumnya yang valid.
print(f"\nJumlah nilai NaN sebelum diisi: {data['harga'].isnull().sum()}")
data['harga'].fillna(method='ffill', inplace=True)
print(f"Jumlah nilai NaN setelah diisi: {data['harga'].isnull().sum()}")

# Normalisasi/Skala Data
# Scaling sangat penting untuk LSTM/Neural Networks
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(data)

# ==============================================================================
# 3. PEMBENTUKAN DATASET UNTUK LSTM
# ==============================================================================

# Fungsi untuk membuat dataset urutan (sequences)
def create_dataset(dataset, look_back=1):
    """
    Mengubah array menjadi dataset yang dapat digunakan untuk supervised learning.
    look_back: Jumlah hari/time step yang digunakan untuk memprediksi hari berikutnya.
    """
    X, Y = [], []
    for i in range(len(dataset) - look_back):
        # Ambil urutan masa lalu (X)
        a = dataset[i:(i + look_back), 0]
        X.append(a)
        # Ambil nilai masa depan (Y)
        Y.append(dataset[i + look_back, 0])
    return np.array(X), np.array(Y)

# Definisikan panjang look_back (time steps). Umumnya 30, 60, atau 90 hari.
look_back = 60

# Buat dataset
X, y = create_dataset(scaled_data, look_back)

# Bagi data menjadi Training dan Test (misalnya 80% Training, 20% Test)
train_size = int(len(X) * 0.80)
test_size = len(X) - train_size
X_train, X_test = X[0:train_size], X[train_size:len(X)]
y_train, y_test = y[0:train_size], y[train_size:len(y)]

# Reshape input ke format [samples, time steps, features] yang dibutuhkan LSTM
# Di sini: [jumlah_data, look_back, 1 (karena hanya 1 fitur/kolom harga)]
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

print(f"\nBentuk X_train setelah reshape: {X_train.shape}")
print(f"Bentuk X_test setelah reshape: {X_test.shape}")

# ==============================================================================
# 4. MEMBANGUN DAN MELATIH MODEL LSTM
# ==============================================================================

# Bangun Model LSTM
model = Sequential()
# Tambahkan layer LSTM dengan 50 neuron, return_sequences=True untuk layer selanjutnya
model.add(LSTM(50, return_sequences=True, input_shape=(look_back, 1)))
# Tambahkan layer LSTM kedua dengan 50 neuron
model.add(LSTM(50, return_sequences=False))
# Tambahkan layer Dense (output layer)
model.add(Dense(1))

# Kompilasi Model
# Gunakan optimizer Adam dan Mean Squared Error (MSE) sebagai fungsi loss
model.compile(optimizer='adam', loss='mean_squared_error')

print("\nRingkasan Model:")
model.summary()

# Latih Model
# epoch: Jumlah iterasi pelatihan
# batch_size: Jumlah sampel yang diproses sebelum model diperbarui
history = model.fit(X_train, y_train, epochs=20, batch_size=32, verbose=2,
                    validation_data=(X_test, y_test))

print("\nModel telah selesai dilatih.")

# ==============================================================================
# 5. EVALUASI DAN VISUALISASI HASIL
# ==============================================================================

# Prediksi pada data test
train_predict = model.predict(X_train)
test_predict = model.predict(X_test)

# Balikkan skala untuk mendapatkan nilai harga aktual
train_predict = scaler.inverse_transform(train_predict)
y_train_actual = scaler.inverse_transform(y_train.reshape(-1, 1))
test_predict = scaler.inverse_transform(test_predict)
y_test_actual = scaler.inverse_transform(y_test.reshape(-1, 1))

# Hitung RMSE (Root Mean Squared Error) untuk evaluasi
from sklearn.metrics import mean_squared_error
train_rmse = np.sqrt(mean_squared_error(y_train_actual, train_predict))
test_rmse = np.sqrt(mean_squared_error(y_test_actual, test_predict))

print(f"\nRoot Mean Squared Error (RMSE) Training: {train_rmse:.2f}")
print(f"Root Mean Squared Error (RMSE) Testing: {test_rmse:.2f}")

# Persiapan untuk Visualisasi
# Geser prediksi pelatihan untuk plot yang benar
train_plot = np.empty_like(scaled_data)
train_plot[:, :] = np.nan
train_plot[look_back:len(train_predict) + look_back, :] = train_predict

# Geser prediksi pengujian untuk plot yang benar
test_plot = np.empty_like(scaled_data)
test_plot[:, :] = np.nan
# CORRECTED: The start index for test_plot was incorrect.
# It should start after the train_predict values, accounting for the look_back period.
test_start_idx = look_back + len(train_predict)
test_end_idx = look_back + len(train_predict) + len(test_predict)
test_plot[test_start_idx : test_end_idx, :] = test_predict

# ==================================
# Visualisasi Hasil
# ==================================
plt.figure(figsize=(15, 6))

# Plot Harga Aktual
plt.plot(data.index, scaler.inverse_transform(scaled_data), label='Harga Aktual', color='blue')

# Plot Prediksi Training
# Indeks untuk data training dimulai dari look_back
train_indices = data.index[look_back : len(train_predict) + look_back]
plt.plot(train_indices, train_predict, label='Prediksi Training', color='green')

# Plot Prediksi Testing
# Indeks untuk data testing
# CORRECTED: Align test_indices with the corrected test_plot indexing.
test_indices = data.index[test_start_idx : test_end_idx]
plt.plot(test_indices, test_predict, label='Prediksi Testing', color='red')

plt.title('Prediksi Harga Telur Menggunakan LSTM')
plt.xlabel('Tanggal')
plt.ylabel('Harga')
plt.legend()
plt.grid(True)
plt.show()

# Simpan plot
plt.savefig('lstm_price_prediction.png')
print("Plot hasil prediksi disimpan sebagai 'lstm_price_prediction.png'")